---
title: 成长|时间管理
author: xiaoyu
date: '2020-09-24'
slug: 成长-时间管理
categories:
  - notes
  - daily
tags:
  - thoughts
  - 个人成长
draft: yes
---
首先说明这不是一篇心灵鸡汤，而是我惨痛的教训记录，和一些坦率的思考。我曾经听过很多人讲过时间管理的方法。但是有的方法并不适合自己，或者说：不适合我的个性与做事的风格。我也曾经尝试过相当多的方法：例如写time log, 写todo list, 用桌面日历，或任务管理软件, 按照优先级划分任务。但是我觉得它们对于我的效率并没有显著地提高，当学业繁忙时，我也不得不连续被迫熬夜，每天拖着疲惫的身躯浑浑噩噩。到底是哪里出了问题呢？以下是我感受最深的一些方面，我个人认为是它们严重降低了我的效率，以至于身心备受损耗。

## 专注力

随着年龄渐长，我越来越认为具有专注力强的人才是真正的强者，宛如一把行走世界的尚方宝剑。在我上大学以前，对热爱的事物保持专注对我来说轻而易举，也许因为我每天只需要按部就班地学习，手机也因功能太少，不够智能而对我没有太大的吸引力。我依稀记得：高三时某天我突然悟出了一条能提高我学习效率的方法：即在固定的时间做固定的学科作业。这样我就能摆脱对数学的沉迷，让自己做其他学科的作业。

但是上大学后，一切都发生了变化。经历了短暂的新鲜感后，我意识到我需要对太多的事进行权衡，而这些选择将一步步雕刻着自己。我也终于有了使用手机和电脑的自由。这些电子产品中丰富的资源、网络生活中泛滥的观点令我乐此不疲。阅读、写作，那些需要绝对地专注与独处的活动渐渐远离了我。写到这时我已意识到，自己在这种被动的选择中，获得了许多，却又失去了点什么。

太多的资源让我充分相信自己能够通过努力规划出自己期望的生活，但是太多的观点却又让在做选择时变得前所未有地犹疑不决。当我想要分心时，我得问问自己：自己真的喜欢这样吗？

## 延迟满足

大概每个人都在不同渠道看到过这样一个鸡汤故事：“那些能够延迟满足（指摇铃索要糖果）的小孩在长大后有更大地几率获得成功”。姑且结论是否正确，但是从个人经历来说，学会延迟的确能够提高自己整体的效率。

当我在网络上浏览信息时，我会情不自禁地在不同链接间跳跃，仅仅因为我觉得它们有趣或有用；同样，有时当我在勤勤恳恳地搜索信息时，也仅仅是因为我需要它们。这些活动前提都忽略了一点：我当下是否需要它们？

好奇心与求知欲永远无法被满足，有时这并不是一件好事。我将自己比作一块硕大的海绵，在知识的海洋前，不加选择（内容、时机）地吸收也只会让自己漂浮在这茫茫的海面上。

---------------------未完待更--------------------

## See Big scope

## “慢”是我的选择吗

## 我为拖沓找了个蹩脚的借口