---
title: 成长|如何进步
author: xiaoyu
date: '2020-09-13'
categories:
  - TED
tags:
  - talks
  - thoughts
  - 个人成长
draft: yes
---
最近特别关注个人的成长问题。心中一直积蓄着什么能量，总想着做点什么。受到学弟公众号的启发，我意识到生活中其实有很多思考都值得记录下来。我会坚持读一些这方面的书籍、看一些视频讲座、多与不同的人交谈以倾听他们的看法。今天我在TED上看了几个视频，这里将记录下其中的内容。这是该系列的第一篇，希望自己能够坚持下去~

# How to get better at things we care about?

演讲者为$Eduarido\quad Brice\tilde{n}o$。这篇演讲希望帮助解决付出和收获之间不对等的困惑————很多时候，我们感到自己付出了太多的时间精力，但是却在自己热爱的事物前止步不前，似乎收获不大。一方面可能是由于我们没有学会规划与记录；另一方面则是我们努力的方向出了问题。

他认为，我们所有为之奋斗的事物实际上都包含了两个空间：学习空间（Learn Zone）和展示空间（Performance Zone）。我们之所以感到停滞，是因为我们花了太多的在展示空间上。他认为学习最好的方法是在这两个空间中交替来回，以使自己呈现螺旋式上升的状态。

那么什是学习空间呢？它指的是一个可以进行试错、反馈与自我训练、发散实验的空间，学习空间里的风险尽可能小，自己享有充分的自由去探索不同技能，发展自己的潜能，包含重复与调整，以及向专业人员寻求反馈。目标是为了获得进步，无需考虑失败的成本。与之相反的是，展示空间是一个需要尽最大努力的高风险空间。（狄墨西尼的例子，他如何纠正动作、学习表演、在海边练习。而不仅仅是为了学习作为律师的技能。）

> 我们在学习去积攒技能，然后将其应用于展现区。

他运用了著名歌手碧昂斯的例子，当她和她的团队在进行演唱会时，她们存在于展示空间里。她们要尽最大的努力做到最好，给观众留下一个好印象，避免演出差错；当她们回到酒店，观看录像视频时，他们回到了学习空间，进行复盘，获取反馈，写下笔记，从中学习并进行自我训练。慢慢地他们获得了他们想要的进步。

> 我们之所以在展现区耗费大量时间，是因为我们通常不必要地将环境置于高风险的状态...即使是在学校里。

学习区存在于低风险中，展示区则更像一片波涛汹涌的浪花。但是，我们不能抗拒犯错，我们要学会在浪花中寻找一片相对低风险的岛屿。例如与自己信任的导师交流，以获得定期的反馈。